### ISSUE TITLE
potential bug report

### ISSUE THREAD

**Issue by he-yang** [jpdevries/JSONarea#2]
Hi,
I've tried to use the same way to validate a json by:
`JSON.parse( json )`
If you try `JSON.parse('1')` or `JSON.parse(1)`, you will not receive error report, but 1.
and obviously, '1' or 1 is not a valid json.
As a result, the above way may not be the best way to valiate a json.

**Comment by jpdevries** [comment]
@he-yang apparently `1` is valid JSON  
![](http://j4p.us/2Q1H2P23080o/Screen%20Shot%202016-05-23%20at%202.59.34%20AM.png)
http://jsonlint.com
